routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('/post', 'PostController');

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    public $fillable = [
        'title', 'sort_description', 'description', 'image', 'status'
    ]; 
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use Illuminate\Http\Request;

class PostController extends Controller
{

    public function index()
    {
        $data['page'] = 'index';
        $data['posts'] = Post::orderBy('id', 'DESC')->paginate(10);
        return view('post.index', $data);
    }

    public function create() 
    {
        $data['page'] = 'create';
        return view('post.index', $data);
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'title'  => 'required|max:255',
            'status' => 'required|in:Active,Inactive',
        ]);

        $image = '';
        if ($request->hasFile('image')) {
            $file = $request->file('image');
            $image = time() . '_post_' . $file->getClientOriginalName();
            $file->move('image/', $image);
        }

        Post::create([
            'title' => $request->title,
            'sort_description' => $request->sort_description,
            'description' => $request->description,
            'status' => $request->status,
            'image' => $image,
        ]);

        return redirect()->back()->with('success', 'Post save successfully');

    }

    public function edit($id) 
    {
        $data['page'] = 'edit';
        $data['post'] = Post::find($id);
        
        return view('post.index', $data);
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'title'  => 'required|max:255',
            'status' => 'required|in:Active,Inactive',
        ]);

        $post = Post::find($id);

        if(isset($post)) {
            $image = $post->image;
            if ($request->hasFile('image')) {
                if ($post->image){
                    unlink(public_path('/image/').$post->image);
                }
                $file = $request->file('image');
                $image = time() . '_post_' . $file->getClientOriginalName();
                $file->move('image/', $image);
            }
    
            $post->update([
                'title' => $request->title,
                'sort_description' => $request->sort_description,
                'description' => $request->description,
                'status' => $request->status,
                'image' => $image,
            ]);
    
            return redirect()->back()->with('success', 'Post update successfully');
        } else {
            return redirect()->back()->with('error', 'Somethng went wrong. Please try agin.');
        }
    }

    public function show($id) 
    {
        $data['page'] = 'show';
        $data['post'] = Post::find($id);
        
        return view('post.index', $data);
    }

    public function destroy($id) 
    {
        $post = Post::find($id);
        
        if(isset($post)) {
            if ($post->image){
                unlink(public_path('/image/').$post->image);
            }
            $post->delete();
            return redirect()->back()->with('success', 'Post delete successfully');
        } else {
            return redirect()->back()->with('error', 'Somethng went wrong. Please try agin.');
        }
    }





}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/post.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>@yield('title')</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body style="background-color: rgb(219, 219, 219)">
    @yield('content')
</body>
</html>

resources/views/post/index.blade.php
@extends('layouts.post')

@section('title')
    Post
@endsection

@section('content')
    <div class="container">
    
        <div class="row d-flex justify-content-center">
            <h1>Simple CRUD with Laravel</h1>

            @if (session('success') || session('error'))
                <div class="col-md-10 mt-5">
                    @if (session('success'))
                        <div class="alert alert-success" role="alert">
                            {{ session('success') }}
                        </div>
                    @elseif(session('error'))
                        <div class="alert alert-danger" role="alert">
                            {{ session('error') }}
                        </div>
                    @endif
                </div>
            @endif
            @if($page == 'index')
                <div class="col-md-10 mt-5">
                    <div class="card">
                        <div class="card-header">
                            <a href="{{ route('post.create') }}" class="right">Create New</a>
                        </div>
                        <div class="card-body">
                            <table class="table table-border table-hover">
                                <thead>
                                <tr>
                                    <th>SL</th>
                                    <th>Title</th>
                                    <th>Short Description</th>
                                    <th>Status</th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody>
                                @if(count($posts) > 0 && isset($posts))
                                    @foreach($posts as $key => $post)
                                        <tr>
                                            <td>{{ ++$key }}</td>
                                            <td>{{ $post->title }}</td>
                                            <td>{{ $post->sort_description }}</td>
                                            <td>{{ $post->status }}</td>
                                            <td>
                                                <div class="btn-group">
                                                    <button type="button" class="btn btn-info btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                        Action
                                                    </button>
                                                    <div class="dropdown-menu">
                                                        <a class="dropdown-item" href="{{ route('post.edit', $post->id) }}">Edit</a>
                                                        <a class="dropdown-item" href="{{ route('post.show', $post->id) }}">View</a>
                                                        <a class="dropdown-item" onclick="deletePost(`{{ route('post.destroy', $post->id) }}`)" href="#">Delete</a>

                                                
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach
                                @else
                                    <tr>
                                        <td colspan="5" align="center">No data found</td>
                                    </tr>
                                @endif
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <td class="text-center" colspan="5" align="center">
                                            {{ $posts->links() }}
                                        </td>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            @elseif($page == 'create' || $page == 'edit')
                <div class="col-md-10 mt-5">
                    <div class="card">
                        <div class="card-header">
                            <a href="{{ route('post.index') }}" class="right">Back To list</a>
                        </div>
                        <div class="card-body">
                            <form method="POST" action="{{ $page == 'create' ? route('post.store') : route('post.update', $post->id) }}" enctype="multipart/form-data">
                                @csrf
                                @if($page == 'edit')
                                    @method('PUT')
                                @endif
                                <div class="form-group">
                                    <label for="title">Title</label>
                                    <input type="text" class="form-control" value="{{ old('title', isset($post) ? $post->title : '') }}" name="title" id="title" placeholder="Title">
                                    @error('title')
                                      <span class="text-danger">
                                          <strong>{{ $message }}</strong>
                                      </span>
                                    @enderror
                                  </div>
                                  <div class="form-group">
                                      <label for="short_description">Shot Description</label>
                                      <textarea type="text" class="form-control" name="sort_description" id="sort_description" placeholder="Shot Description">{{ old('sort_description', isset($post) ? $post->sort_description : '') }}</textarea>
                                      @error('short_description')
                                      <span class="text-danger">
                                          <strong>{{ $message }}</strong>
                                      </span>
                                      @enderror
                                  </div>

                                  <div class="form-group">
                                      <label for="description">Description</label>
                                      <textarea type="text" rows="10" class="form-control" name="description" id="description" placeholder="Description">{{ old('description', isset($post) ? $post->description : '') }}</textarea>
                                      @error('description')
                                      <span class="text-danger">
                                          <strong>{{ $message }}</strong>
                                      </span>
                                      @enderror
                                  </div>

                                  <div class="form-group">
                                      <label for="image">Image</label>
                                      <input type="file" accept="image/*" class="form-control" name="image" id="image">
                                      @error('image')
                                      <span class="text-danger">
                                          <strong>{{ $message }}</strong>
                                      </span>
                                      @enderror
                                  </div>

                                  <div class="form-group">
                                      <label for="status">Status</label>
                                      <select class="form-control" name="status" id="status">
                                          <option selected disabled hidden>Select Status</option>
                                          <option value="Active" {{ isset($post) && $post->status == 'Active' ? 'selected' : '' }}>Active</option>
                                          <option value="Inactive" {{ isset($post) && $post->status == 'Inactive' ? 'selected' : '' }}>Inactive</option>
                                      </select>
                                      @error('status')
                                      <span class="text-danger">
                                          <strong>{{ $message }}</strong>
                                      </span>
                                      @enderror
                                  </div>
                                  
                                  <button type="submit" class="btn btn-primary">Submit</button>

                            </form>
                        </div>
                    </div>
                </div>

            @elseif($page == 'show')
            <div class="col-md-10 mt-5">
                <div class="card">
                    <div class="card-header">
                        <a href="{{ route('post.index') }}" class="right">Back To list</a>
                    </div>
                    <div class="card-body">
                        <table class="table table-border table-hover">
                            <tr>
                                <th>Title</th>
                                <td>{{ $post->title }}</td>
                            </tr>
                            <tr>
                                <th>Sort Description</th>
                                <td>{{ $post->sort_description }}</td>
                            </tr>
                            <tr>
                                <th>Description</th>
                                <td>{{ $post->description }}</td>
                            </tr>

                            <tr>
                                <th>Status</th>
                                <td>{{ $post->status }}</td>
                            </tr>
                            <tr>
                                <th>Image</th>
                                <td> 
                                    @if($post->image)
                                        <img width="30%" src="{{ asset('image/'. $post->image) }}" alt="{{ $post->title }}">
                                    @else
                                        <small class="text-danger">Image not found</small>
                                    @endif
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
            @endif


        </div>
    </div>


    @if($page == 'index')
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Delete</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              Are you sure delete this post ??
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <button type="button" onclick="event.preventDefault();document.getElementById('deleteForm').submit();" class="btn btn-danger">Delete</button>

              <form id="deleteForm" action="" method="POST" class="d-none">
                @csrf
                @method('DELETE')
              </form>               
            </div>
          </div>
        </div>
      </div>
      <script>
          function deletePost(url) {
            $('#deleteForm').attr('action', url);
            $('#deleteModal').modal('show');
          }
      </script>
    @endif
    
@endsection